// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeBook.Data;

#nullable disable

namespace RecipeBook.Migrations
{
    [DbContext(typeof(RecipeBookDbContext))]
    [Migration("20211218103116_fewMoreInitialData")]
    partial class fewMoreInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RecipeBook.Data.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 5m,
                            Name = "चीनी",
                            RecipeId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 5m,
                            Name = "मैदा",
                            RecipeId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Amount = 5m,
                            Name = "तेल",
                            RecipeId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Amount = 5m,
                            Name = "पके सूखे आलू",
                            RecipeId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            Amount = 2m,
                            Name = "मटर",
                            RecipeId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            Amount = 2m,
                            Name = "प्याज",
                            RecipeId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            Amount = 2m,
                            Name = "दाल",
                            RecipeId = 2L
                        },
                        new
                        {
                            Id = 8L,
                            Amount = 3m,
                            Name = "चटनी",
                            RecipeId = 2L
                        });
                });

            modelBuilder.Entity("RecipeBook.Data.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "जलेबी उत्तर भारत, पाकिस्तान व मध्यपूर्व का एक लोकप्रिय व्यंजन है। इसका आकार पेंचदार होता है और स्वाद करारा मीठा। इस मिठाई की धूम भारतीय उपमहाद्वीप से शुरू होकर पश्चिमी देश स्पेन तक जाती है। इस बीच भारत, बांग्लादेश, पाकिस्तान, ईरान के साथ तमाम अरब मुल्कों में भी यह खूब जानी-पहचानी है।",
                            ImageUrl = "https://punampaul.com/wp-content/uploads/2019/10/Jalebi-Recipe.jpg",
                            Name = "जलेबी"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "समोसा एक तला हुआ या बेक किया हुआ भरवां अल्पाहार व्यंजन है। इसमें प्रायः मसालेदार भुने या पके हुए सूखे आलू, या इसके अलावा मटर, प्याज, दाल, कहीम कहीं मांसा भी भरा हो सकता है। इसका आकार प्रायः तिकोना होता है किन्तु आकार और नाप भिन्न-भिन्न स्थानों पर बदल सकता है। अधिकतर ये चटनी के संग परोसे जाते हैं।",
                            ImageUrl = "https://static.langimg.com/thumb/msid-76956747,width-680,resizemode-3/navbharat-times.jpg",
                            Name = "समोसा"
                        });
                });

            modelBuilder.Entity("RecipeBook.Data.Ingredient", b =>
                {
                    b.HasOne("RecipeBook.Data.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeBook.Data.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
